### ISSUE TITLE
Bookmark page's footer is out of place

### ISSUE THREAD

**Issue by codingonHP** [creativecommons/ccsearch-browser-extension#33] opened 2019-10-08 16:23 UTC
### Issue
Footer on the Bookmarks page is out of place

![image](https://user-images.githubusercontent.com/7105293/66413851-da592980-ea15-11e9-8388-525044a659e6.png)

### Solution
CSS needs work

**Comment by ashishdutta007** [comment] 2019-10-08 17:41
Will fix this

**Comment by makkoncept** [comment] 2019-10-08 22:53
closing as it's a duplicate of #31.

**Closed by makkoncept** 2019-10-08 22:53 UTC
